image: registry.labs.nic.cz/turris/pyuci

stages:
  - test
  - pages

python2:
  stage: test
  before_script:
    - pip install .
    - export LD_LIBRARY_PATH=/usr/local/lib
  script:
    - python -m pytest tests

python3:
  stage: test
  before_script:
    - pip3 install .
    - export LD_LIBRARY_PATH=/usr/local/lib
  script:
    - python3 -m pytest tests

# Let's generate coverage only using Python3
pages:
  stage: pages
  before_script:
    - COVERAGE=y python3 setup.py install
    - export LD_LIBRARY_PATH=/usr/local/lib
    - python3 -m pytest tests
  script:
    - lcov --capture --no-external --base-directory . --directory build/temp.* --output-file coverage.info
    - genhtml coverage.info --output-directory public/coverage-c
  artifacts:
    when: on_success
    paths:
      - public
  only:
  - master
